//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class FollowUser
    {
        public string AspNetUserId { get; set; }
        public Nullable<int> FollowerId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual User User { get; set; }
    }
}
